// plugins
import './modules/fullPage';
// modules
import './modules/common';
import './modules/sliders';
import './modules/barbaInst';
import './modules/animation';
import './modules/header';
import './modules/custom-cursor';
import './modules/popup';
import './modules/sendForm';
